---
- name: Create snapshot
  vmware_guest_snapshot:
  hostname: 192.168.1.207
  username: administrator@vsphere.local
  password: Passwd@
  datacenter: Datacenter1
  folder: /
#    name: Dummy
  state: present
  snapshot_name: snap1
  description: snap1_description
  delegate_to: localhost
