---
- hosts: wordpress1
  gather_facts: fals
  become_method: yes

  tasks:  
  - name: Download WordPress
    get_url:
      url=https://wordpress.org/latest.tar.gz
      dest=/tmp/wordpress.tar.gz
      validate_certs=no
    sudo: yes

  - name: Extract WordPress
    unarchive:
      src=/tmp/wordpress.tar.gz dest=/var/www/
      copy=no
    sudo: yes

  - name: Install MySQL-client
    apt:
      name: "{{ item }}"
    with_items:
    - mariadb-client-core-10.1
    - mysql-client-core-5.7 
    

