---
- name: About to run this test yml script
  hosts: 192.168.0.106
  gather_facts: true
  become_method: yes
  tasks:
  - import_role:
      name: myroles/snapshot
    delegate_to: localhost

  - import_role:
      name: myroles/docker
